# Generated by Django 4.2.6 on 2024-04-23 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='appliancesUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=1000)),
                ('item_description', models.CharField(max_length=100000000000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='coverImages/Apps/')),
            ],
        ),
        migrations.CreateModel(
            name='babypUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=1000)),
                ('item_description', models.CharField(max_length=100000000000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='coverImages/Apps/')),
            ],
        ),
        migrations.CreateModel(
            name='booksetcUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=1000)),
                ('item_description', models.CharField(max_length=100000000000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='coverImages/Apps/')),
            ],
        ),
        migrations.CreateModel(
            name='computingUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=1000)),
                ('item_description', models.CharField(max_length=100000000000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='coverImages/Apps/')),
            ],
        ),
        migrations.CreateModel(
            name='electronicsUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=1000)),
                ('item_description', models.CharField(max_length=100000000000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='coverImages/Apps/')),
            ],
        ),
        migrations.CreateModel(
            name='fashionUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=1000)),
                ('item_description', models.CharField(max_length=100000000000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='coverImages/Apps/')),
            ],
        ),
        migrations.CreateModel(
            name='gamingUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=1000)),
                ('item_description', models.CharField(max_length=100000000000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='coverImages/Apps/')),
            ],
        ),
        migrations.CreateModel(
            name='gardenandcoUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=1000)),
                ('item_description', models.CharField(max_length=100000000000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='coverImages/Apps/')),
            ],
        ),
        migrations.CreateModel(
            name='healthandcoUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=1000)),
                ('item_description', models.CharField(max_length=100000000000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='coverImages/Apps/')),
            ],
        ),
        migrations.CreateModel(
            name='homeandcoUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=1000)),
                ('item_description', models.CharField(max_length=100000000000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='coverImages/Apps/')),
            ],
        ),
        migrations.CreateModel(
            name='industrialandcoUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=1000)),
                ('item_description', models.CharField(max_length=100000000000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='coverImages/Apps/')),
            ],
        ),
        migrations.CreateModel(
            name='musicalUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=1000)),
                ('item_description', models.CharField(max_length=100000000000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='coverImages/Apps/')),
            ],
        ),
        migrations.CreateModel(
            name='petandcoUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=1000)),
                ('item_description', models.CharField(max_length=100000000000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='coverImages/Apps/')),
            ],
        ),
        migrations.CreateModel(
            name='phonesandcoUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=1000)),
                ('item_description', models.CharField(max_length=100000000000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='coverImages/Apps/')),
            ],
        ),
        migrations.CreateModel(
            name='sportingUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=1000)),
                ('item_description', models.CharField(max_length=100000000000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='coverImages/Apps/')),
            ],
        ),
        migrations.CreateModel(
            name='supermarketUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=1000)),
                ('item_description', models.CharField(max_length=100000000000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='coverImages/Apps/')),
            ],
        ),
    ]
