# Generated by Django 4.2.6 on 2023-10-23 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='appUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('image', models.ImageField(height_field=100, upload_to='', width_field=100)),
                ('file', models.FileField(upload_to='apps.html')),
            ],
        ),
        migrations.CreateModel(
            name='bookUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('image', models.ImageField(height_field=100, upload_to='', width_field=100)),
                ('upload', models.FileField(upload_to='books.html')),
            ],
        ),
        migrations.CreateModel(
            name='miscUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('image', models.ImageField(height_field=100, upload_to='', width_field=100)),
                ('upload', models.FileField(upload_to='misc.html')),
            ],
        ),
        migrations.CreateModel(
            name='moviesUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('image', models.ImageField(height_field=100, upload_to='', width_field=100)),
                ('upload', models.FileField(upload_to='movies.html')),
            ],
        ),
        migrations.CreateModel(
            name='requestUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.CharField(max_length=10000000000000000)),
            ],
        ),
    ]
