# Generated by Django 4.2.6 on 2023-10-23 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestupload',
            old_name='upload',
            new_name='requesttitle',
        ),
    ]
