# Generated by Django 4.2.6 on 2023-10-23 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theApp', '0003_bookrequest_miscrequest_moviesrequest_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apprequest',
            old_name='requesttitle',
            new_name='requestname',
        ),
        migrations.RenameField(
            model_name='bookrequest',
            old_name='requesttitle',
            new_name='requestname',
        ),
        migrations.RenameField(
            model_name='miscrequest',
            old_name='requesttitle',
            new_name='requestname',
        ),
        migrations.RenameField(
            model_name='moviesrequest',
            old_name='requesttitle',
            new_name='requestname',
        ),
    ]
