# Generated by Django 4.2.6 on 2023-10-23 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theApp', '0004_rename_requesttitle_apprequest_requestname_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='appUpload',
        ),
        migrations.DeleteModel(
            name='bookUpload',
        ),
        migrations.DeleteModel(
            name='miscUpload',
        ),
        migrations.DeleteModel(
            name='moviesUpload',
        ),
    ]
