# Generated by Django 4.2.6 on 2023-10-23 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theApp', '0005_delete_appupload_delete_bookupload_delete_miscupload_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='appUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('image', models.ImageField(height_field=100, upload_to='', width_field=100)),
                ('file', models.FileField(upload_to='apps.html')),
            ],
        ),
        migrations.CreateModel(
            name='bookUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('image', models.ImageField(height_field=100, upload_to='', width_field=100)),
                ('file', models.FileField(upload_to='books.html')),
            ],
        ),
        migrations.CreateModel(
            name='miscUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('image', models.ImageField(height_field=100, upload_to='', width_field=100)),
                ('file', models.FileField(upload_to='misc.html')),
            ],
        ),
        migrations.CreateModel(
            name='moviesUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('image', models.ImageField(height_field=100, upload_to='', width_field=100)),
                ('file', models.FileField(upload_to='movies.html')),
            ],
        ),
    ]
