# Generated by Django 4.2.6 on 2023-10-23 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theApp', '0006_appupload_bookupload_miscupload_moviesupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appupload',
            name='file',
            field=models.FileField(upload_to='Apps/'),
        ),
        migrations.AlterField(
            model_name='bookupload',
            name='file',
            field=models.FileField(upload_to='Books/'),
        ),
        migrations.AlterField(
            model_name='miscupload',
            name='file',
            field=models.FileField(upload_to='Others/'),
        ),
        migrations.AlterField(
            model_name='moviesupload',
            name='file',
            field=models.FileField(upload_to='Movies/'),
        ),
    ]
