# Generated by Django 4.2.6 on 2023-11-13 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theApp', '0008_alter_appupload_file_alter_appupload_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appupload',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='coverImages/Apps/'),
        ),
        migrations.AlterField(
            model_name='bookupload',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='coverImages/Books/'),
        ),
        migrations.AlterField(
            model_name='miscupload',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='coverImages/Others/'),
        ),
        migrations.AlterField(
            model_name='moviesupload',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='coverImages/Videos/'),
        ),
    ]
